name: "Update Angular Action"
on:
  schedule:
    - cron: '30 5 * * 1,3,5'

# --- ADD THIS BLOCK ---
permissions:
  contents: write      # Allows pushing code
  pull-requests: write # Allows opening PRs
# ----------------------

jobs:
  ngxUptodate:
    runs-on: ubuntu-latest
    steps:
      - name: Updating ng dependencies
        uses: fast-facts/ng-update@v1
        with:
          base-branch: main
          project-path: ./crud-angular
          repo-token: ${{ secrets.GITHUB_TOKEN }}
