name: "Update Angular Action"
on: 
  schedule:
    - cron: '30 5 * * 1,3,5'
  
  # 1. Adds the "Run workflow" button in GitHub Actions tab
  workflow_dispatch: 

  # 2. Runs on every push to the main branch
  push:
    branches:
      - main 

permissions:
  contents: write      
  pull-requests: write 

jobs:
  ngxUptodate:
    runs-on: ubuntu-latest
    steps:
      - name: Updating ng dependencies 
        uses: fast-facts/ng-update@v1
        with:
          base-branch: main
          project-path: ./crud-angular
          repo-token: ${{ secrets.GITHUB_TOKEN }}
